import os
from pathlib import Path


def _path_from_env(var_name: str, default: Path) -> Path:
    env_value = os.environ.get(var_name)
    if env_value:
        return Path(env_value).expanduser()
    return default


PROJECT_ROOT = _path_from_env("NHIS_GI_PROJECT_ROOT", Path(__file__).resolve().parent.parent)
DATA_DIR = PROJECT_ROOT / "data"

NHIS_RAW_ROOT = _path_from_env("NHIS_RAW_ROOT", DATA_DIR / "NHIS_raw")
LMF_RAW_ROOT = _path_from_env("LMF_RAW_ROOT", DATA_DIR / "LMF_raw")

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

# Primary analysis includes every available survey year from 1997 through 2018.
ANALYSIS_YEARS = list(range(1997, 2019))
OPTIONAL_SENSITIVITY_YEARS = []

YEAR_VARIABLE_MAP = {
    1997: {
        "person_key": "PX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACE_P",
        "hispanic": "HISPAN_P",
        "education": "EDUC",
        "region": "REGION",
        "poverty": "RAT_CAT",
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": None,
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    1998: {
        "person_key": "PX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACE_P",
        "hispanic": "HISPAN_P",
        "education": "EDUC",
        "region": "REGION",
        "poverty": "RAT_CAT",
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": None,
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    1999: {
        "person_key": "PX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACER_P",
        "hispanic": "HISPANCR",
        "education": "EDUC",
        "region": "REGION",
        "poverty": "RAT_CAT",
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": None,
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    2000: {
        "person_key": "PX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "RACERP_I",
        "hispanic": "HISPAN_I",
        "education": "EDUC",
        "region": "REGION",
        "poverty": "RAT_CAT",
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    2001: {
        "person_key": "PX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "RACERP_I",
        "hispanic": "HISPAN_I",
        "education": "EDUC",
        "region": "REGION",
        "poverty": "RAT_CAT",
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    2002: {
        "person_key": "PX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "RACERP_I",
        "hispanic": "HISPAN_I",
        "education": "EDUC",
        "region": "REGION",
        "poverty": "RAT_CAT",
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    2003: {
        "person_key": "PX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": "EDUC",
        "region": "REGION",
        "poverty": "RAT_CAT",
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    2004: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": None,
        "age": None,
        "sex": None,
        "race": None,
        "hispanic": None,
        "education": None,
        "region": None,
        "poverty": None,
        "marital": None,
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    2005: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRATUM",
        "design_psu": "PSU",
    },
    2006: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGER01",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU_P",
    },
    2007: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL",
        "dm_insulin": "INSLN",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU",
    },
    2008: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU",
    },
    2009: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU",
    },
    2010: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU",
    },
    2011: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU_P",
    },
    2012: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU",
    },
    2013: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU",
    },
    2014: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU",
    },
    2015: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV",
        "dm_age": "DIBAGE",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "STRAT_P",
        "design_psu": "PSU_P",
    },
    2016: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV1",
        "dm_age": "DIBAGE1",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL1",
        "dm_insulin": "INSLN1",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "PSTRAT",
        "design_psu": "PSU",
    },
    2017: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV1",
        "dm_age": "DIBAGE1",
        "dm_duration": "DIFAGE2",
        "dm_pills": None,
        "dm_insulin": None,
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "PSTRAT",
        "design_psu": "PSU",
    },
    2018: {
        "person_key": "FPX",
        "hhx": "HHX",
        "fmx": "FMX",
        "survey_year_col": "SRVY_YR",
        "intv_qrt": "INTV_QRT",
        "age": "AGE_P",
        "sex": "SEX",
        "race": "MRACRPI2",
        "hispanic": "HISPAN_I",
        "education": None,
        "region": "REGION",
        "poverty": None,
        "marital": "R_MARITL",
        "canev": "CANEV",
        "cnkind7": "CNKIND7", "canage7": "CANAGE7",
        "cnkind8": "CNKIND8", "canage8": "CANAGE8",
        "cnkind9": "CNKIND9", "canage9": "CANAGE9",
        "cnkind13": "CNKIND13", "canage13": "CANAGE13",
        "cnkind19": "CNKIND19", "canage19": "CANAGE19",
        "cnkind21": "CNKIND21", "canage21": "CANAGE21",
        "cnkind25": "CNKIND25", "canage25": "CANAGE25",
        "dm_ever": "DIBEV1",
        "dm_age": "DIBAGE1",
        "dm_duration": "DIFAGE2",
        "dm_pills": "DIBPILL1",
        "dm_insulin": "INSLN1",
        "smoking_ever": "SMKEV",
        "smoking_status": "SMKSTAT2",
        "bmi": "BMI",
        "afford_rx": "AHCAFYR1",
        "weight_sa": "WTFA_SA",
        "design_strata": "PSTRAT",
        "design_psu": "PPSU",
    },
}

GI_SITES = {
    "colon": {"cnkind": "cnkind7", "canage": "canage7"},
    "esophagus": {"cnkind": "cnkind8", "canage": "canage8"},
    "gallbladder": {"cnkind": "cnkind9", "canage": "canage9"},
    "liver": {"cnkind": "cnkind13", "canage": "canage13"},
    "pancreas": {"cnkind": "cnkind19", "canage": "canage19"},
    "rectum": {"cnkind": "cnkind21", "canage": "canage21"},
    "stomach": {"cnkind": "cnkind25", "canage": "canage25"},
}

GI_SITE_FLAGS = {
    "colon": "CNKIND7",
    "esophagus": "CNKIND8",
    "gallbladder": "CNKIND9",
    "liver": "CNKIND13",
    "pancreas": "CNKIND19",
    "rectum": "CNKIND21",
    "stomach": "CNKIND25",
}

GI_SITE_AGES = {
    "colon": "CANAGE7",
    "esophagus": "CANAGE8",
    "gallbladder": "CANAGE9",
    "liver": "CANAGE13",
    "pancreas": "CANAGE19",
    "rectum": "CANAGE21",
    "stomach": "CANAGE25",
}

TRAJECTORY_CATEGORIES = [
    "gi_only",
    "dm_to_gi_lt2y",
    "dm_to_gi_2_10y",
    "dm_to_gi_gt10y",
    "gi_to_dm",
    "same_year",
]

LMF_COLSPECS = [(0, 14), (14, 15), (15, 16), (16, 19), (19, 20), (20, 21), (21, 22), (22, 26), (26, 34), (34, 42)]
LMF_COLNAMES = ["publicid", "eligstat", "mortstat", "ucod_leading", "diabetes", "hyperten", "dodqtr", "dodyear", "wgt_new", "sa_wgt_new"]


# Round 3 extended variable mappings
YEAR_SAMADULT_EXTENSION_MAP = {
    1997: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT1', 'alcohol_freq_past_year': 'ALC12MMO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    1998: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT1', 'alcohol_freq_past_year': 'ALC12MMO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    1999: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT1', 'alcohol_freq_past_year': 'ALC12MMO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2000: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT1', 'alcohol_freq_past_year': 'ALC12MMO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2001: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT1', 'alcohol_freq_past_year': 'ALC12MMO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2002: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': 'HCHLEV', 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT1', 'alcohol_freq_past_year': 'ALC12MMO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2003: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT1', 'alcohol_freq_past_year': 'ALC12MMO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2004: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2005: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2006: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2007: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2008: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2009: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2010: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2011: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2012: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': 'CHLEV', 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    # CHLYR1 in 2013 asks about the past 12 months and is not comparable to
    # the "ever told" construct used in the other mapped years.
    2013: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': None, 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPNO', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2014: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': 'CHLEV', 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPN1', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2015: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': 'CHLEV', 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPN1', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2016: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': 'CHLEV', 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPN1', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2017: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': 'CHLEV', 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPN1', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
    2018: {'hypertension_ever': 'HYPEV', 'cholesterol_high_ever': 'CHLEV', 'chd_ever': 'CHDEV', 'stroke_ever': 'STREV', 'alcohol_status': 'ALCSTAT', 'alcohol_freq_past_year': 'ALC5UPN1', 'phys_mod_freq': 'MODFREQW', 'phys_vig_freq': 'VIGFREQW'},
}

YEAR_PERSONSX_MAP = {
    1997: {"srh": "PHSTAT", "education": "EDUC", "insurance_notcov": None, "insurance_cover": None},
    1998: {"srh": "PHSTAT", "education": "EDUC", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    1999: {"srh": "PHSTAT", "education": "EDUC", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2000: {"srh": "PHSTAT", "education": "EDUC", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2001: {"srh": "PHSTAT", "education": "EDUC", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2002: {"srh": "PHSTAT", "education": "EDUC", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2003: {"srh": "PHSTAT", "education": "EDUC", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2004: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2005: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2006: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2007: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2008: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2009: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2010: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2011: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2012: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2013: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2014: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": None},
    2015: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": "COVER", "insurance_cover65": "COVER65"},
    2016: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": "COVER", "insurance_cover65": "COVER65"},
    2017: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": "COVER", "insurance_cover65": "COVER65"},
    2018: {"srh": "PHSTAT", "education": "EDUC1", "insurance_notcov": "NOTCOV", "insurance_cover": "COVER", "insurance_cover65": "COVER65"},
}

YEAR_FAMILYXX_MAP = {
    1997: {'poverty': 'FRAT_CAT'},
    1998: {'poverty': 'FRAT_CAT'},
    1999: {'poverty': 'FRAT_CAT'},
    2000: {'poverty': 'FRAT_CAT'},
    2001: {'poverty': 'FRAT_CAT'},
    2002: {'poverty': 'FRAT_CAT'},
    2003: {'poverty': 'FRAT_CAT'},
    2004: {'poverty': 'RAT_CAT'},
    2005: {'poverty': 'RAT_CAT'},
    2006: {'poverty': 'RAT_CAT'},
    2007: {'poverty': 'RAT_CAT3'},
    2008: {'poverty': 'RAT_CAT3'},
    2009: {'poverty': 'RAT_CAT3'},
    2010: {'poverty': 'RAT_CAT3'},
    2011: {'poverty': 'RAT_CAT3'},
    2012: {'poverty': 'RAT_CAT3'},
    2013: {'poverty': 'RAT_CAT3'},
    2014: {'poverty': 'RAT_CAT5'},
    2015: {'poverty': 'RAT_CAT5'},
    2016: {'poverty': 'RAT_CAT5'},
    2017: {'poverty': 'RAT_CAT5'},
    2018: {'poverty': 'RAT_CAT5'},
}


# Fields missing from selected local CSV extracts but present in the official
# fixed-width Sample Adult files. Positions are one-based and inclusive, as in
# the corresponding NCHS SAS input programs.
YEAR_SAMADULT_FWF_SUPPLEMENT_MAP = {
    2005: {
        "member": "SAMADULT.DAT",
        "keys": {"srvy_yr": (3, 6), "hhx": (7, 12), "fmx": (16, 17), "person_key": (18, 19)},
        "fields": {"CANAGE7": (132, 133), "CANAGE8": (134, 135), "CANAGE9": (136, 137)},
    },
    2007: {
        "member": "samadult.dat",
        "keys": {"srvy_yr": (3, 6), "hhx": (7, 12), "fmx": (16, 17), "person_key": (18, 19)},
        "fields": {
            "CANAGE25": (213, 214),
            "DIBAGE": (227, 228),
            "DIFAGE2": (229, 230),
            "INSLN": (231, 231),
            "DIBPILL": (232, 232),
        },
    },
    2011: {
        "member": "SAMADULT.dat",
        "keys": {"srvy_yr": (3, 6), "hhx": (7, 12), "fmx": (16, 17), "person_key": (18, 19)},
        "fields": {
            "INTV_QRT": (13, 13),
            "WTFA_SA": (27, 32),
            "REGION": (33, 33),
            "STRAT_P": (34, 36),
            "PSU_P": (37, 38),
            "SEX": (39, 39),
            "HISPAN_I": (40, 41),
            "MRACRPI2": (44, 45),
            "AGE_P": (48, 49),
        },
    },
}


# 2015's outer CSV is a reduced extract, while the existing official archive
# contains the complete public-use Sample Adult CSV. Read the listed fields
# directly rather than relying on inferred fixed-width positions.
YEAR_SAMADULT_ZIP_CSV_SUPPLEMENT_MAP = {
    2015: {
        "member": "samadult.csv",
        "keys": ["SRVY_YR", "HHX", "FMX", "FPX"],
        "fields": [
            "INTV_QRT", "WTFA_SA", "REGION", "STRAT_P", "PSU_P",
            "SEX", "HISPAN_I", "MRACRPI2", "AGE_P", "R_MARITL",
        ],
    },
}


# Local family CSV extracts for these years lost their identifiers. The
# official fixed-width FAMILYXX files retain the keys and poverty recodes.
YEAR_FAMILYXX_FWF_POVERTY_MAP = {
    2009: ("RAT_CAT3", (158, 159)),
    2011: ("RAT_CAT3", (204, 205)),
    2012: ("RAT_CAT3", (204, 205)),
    2013: ("RAT_CAT3", (206, 207)),
    2014: ("RAT_CAT5", (196, 197)),
}
